spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    myKafkaMessageTopic: "henry-module"
    kafkaMessageTopic: "mike-module"
    kafkaMessageGroupId: "msg-group-id"
server:
  port: 8081
